### ISSUE TITLE
Can not update the easybuild program for PyQt-builder

### ISSUE THREAD

**Issue by geoffreyweal** [Python-PyQt/PyQt-builder#15]
Hello

I am updating the easybuild to run PyMOL. This uses your program.

I looked at [PyQt-builder-1.15.4-GCCcore-12.3.0.eb.txt](https://github.com/user-attachments/files/16624608/PyQt-builder-1.15.4-GCCcore-12.3.0.eb.txt) and pretty much made a carbon copy with a slight change to update it to version 1.16.4 (as well as use GCCcore 13.2.0, but thats not important for this issue)

Here is the updated eb file for PyQt-builder-1.16.4: [PyQt-builder-1.16.4-GCCcore-13.2.0.eb.txt](https://github.com/user-attachments/files/16624606/PyQt-builder-1.16.4-GCCcore-13.2.0.eb.txt)

My problem is that when you install by doing ``eb --robot PyQt-builder-1.15.4-GCCcore-12.3.0.eb``, everything works fine. But if I try to install with ``eb --robot PyQt-builder-1.16.4-GCCcore-13.2.0.eb``, it can not find your updated 1.16.4 version of PyQt-builder. 

From what I gather, as this is a pythonbundle script, I think PyQt-builder-1.16.4 just hasn't been uploaded to whereever it needs to be for this to work like for PyQt-builder-1.15.4. 

I was wondering if you guys knew how to fix this.

Cheers

Geoff

**Comment by philthompson10** [comment]
Sorry, I know nothing about easybuild or pythonbundle. I suggest you contact the person who wrote the original script.

**Comment by geoffreyweal** [comment]
Ok cool all good. Thanks.
