### ISSUE TITLE
Default ABI version doesn't match SIP ones

### ISSUE THREAD

**Issue by troopa81** [Python-PyQt/PyQt-builder#25]
PyQt-builder [default](https://github.com/Python-PyQt/PyQt-builder/blob/develop/pyqtbuild/builder.py#L141) abi versions doesn't match SIP ones [12](https://github.com/Python-SIP/sip/blob/main/sipbuild/module/source/12/sip.h.in#L38) [13](https://github.com/Python-SIP/sip/blob/main/sipbuild/module/source/13/sip.h.in#L38)

**Comment by philthompson10** [comment]
These have been updated but it doesn't actually matter if they are not set to the latest versions. If a project needs a specific minimum version then they should explicitly set it their `pyproject.toml`.

**Comment by philthompson10** [comment]
In fact the specification of any minor number is confusing, somewhat arbitrary and unnecessary. It should be left to SIP to decide on a default minor number - PyQt-builder only needs to provide a default major number (ie. 12 or 13).

**Comment by philthompson10** [comment]
See issue #28 for a better description and resolution of the problem.
