### ISSUE TITLE
qmake binary name is hard-coded

### ISSUE THREAD

**Issue by marcusbritanicus** [Python-PyQt/PyQt-builder#4]
Currently, qmake binary name is hard-coded. This causes issues with Qt6. The qmake binary that comes with Qt6 is named as qmake6. Since the binary name is hard-coded to 'qmake', this causes problems when using sip-wheel to build Qt6 wheels.

Please provide a way to specify the qmake binary name.

**Comment by philthompson10** [comment]
The qmake binary name is not hard-coded...

https://pyqt-builder.readthedocs.io/en/latest/command_line_tools.html#cmdoption-qmake

**Comment by marcusbritanicus** [comment]
@philthompson10 Thanks for the quick response...! Perhaps, you can help us a little further. We're using PyQt-Builder to build the QTermWidget python module. [This](https://github.com/doug1234/qtermwidget/blob/Qt6Update/pyqt/pyproject.toml) is the pyproject.toml file we're using.

This results in an error "qmake" not found. How can we incorporate this option `--qmake FILE` in our pyproject.toml?

**Comment by philthompson10** [comment]
You have specified PyQt-builder as a dependency but aren't actually using it. See https://pyqt-builder.readthedocs.io/en/latest/example.html#an-example (specifically the `project-factory` setting).

**Comment by marcusbritanicus** [comment]
@philthompson10 Thanks for the example. As a test I tried building QtCharts module for PyQt6 from source. I'm afraid it fails to build. Here is the error message:

```
  ~/PyQt6_Charts-6.6.0                                                                                                                                                                                                                       5s 󰌠 3.11.8 03:07:29 PM IST
❯ sip-wheel --verbose
pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
sip-wheel: pyproject.toml: 'tool.sip.project.qmake': specify a working qmake or add it to PATH
```

**Comment by philthompson10** [comment]
On 29/03/2024 09:39, Marcus Britanicus wrote:
> @philthompson10 Thanks for the example. As a test I tried building
> QtCharts module for PyQt6 from source. I'm afraid it fails to build.
> Here is the error message:
> 
> ```
>   ~/PyQt6_Charts-6.6.0
> 
> 
>                           5s 󰌠 3.11.8 03:07:29 PM IST
> ❯ sip-wheel --verbose
> pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the
> project metadata is deprecated and will be removed in SIP v7.0.0, use
> '[project]' instead
> sip-wheel: pyproject.toml: 'tool.sip.project.qmake': specify a working
> qmake or add it to PATH
> ```

So use the --qmake option. Note every standard Qt installation has qmake 
and qmake6.

**Comment by marcusbritanicus** [comment]
@philthompson10 Ah thanks. I see that I misunderstood your original message. That was partly because `sip-wheel --help` does not list the `--qmake` option. Thanks a lot for your help!!

**Comment by philthompson10** [comment]
On 29/03/2024 10:04, Marcus Britanicus wrote:
> @philthompson10 Ah thanks. I see that I misunderstood your original
> message. That was partly because `sip-wheel --help` does not list the
> `--qmake` option. Thanks a lot for your help!!

It gives the correct help if you have set project-factory.
